### ISSUE TITLE
rv = reductor(4) TypeError: can't pickle SwigPyObject objects

### ISSUE THREAD

**Issue by aschluter** [mjenior/riptide#4]
Hi,

when I try the last Human-GEM model I got an error in the deepcopy process. Thanks in advance.

>>> model = cobra.io.read_sbml_model("Human-GEM_30112021.xml")
>>> modelRiptide = riptide.contextualize(model)
WARNING: No transcriptome provided. Analyzing most parsimonious state

Initializing model and integrating transcriptomic data...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/agatha/python-virtual-environments/env/lib/python3.6/site-packages/riptide/riptide.py", line 612, in contextualize
    riptide_model = copy.deepcopy(model)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle SwigPyObject objects

**Comment by mjenior** [comment]
This issue sometimes comes up when some of the python 3.6 dependencies aren't up to date. I haven't fully narrowed down which packages it is yet, but if you update python it usually resolves it. I'll get back to you after I do a little more testing and isolate the solution.

**Comment by mjenior-zymergen** [comment]
I see this problem come up occasionally with certain models saved in xml or sbml format. The temporary solution I have found is to save them quickly as a json and read them back in. Usually fixes the issue, and I'm trying to pinpoint a solution without the weird work around.

**Comment by mjenior** [comment]
This turns out to be an issue with an incompatibility with pickling particular objects within the DictList cobrapy data structure. This becomes problematic when trying to parallelize growth simulations. The latest version of ritpide should fix this issue.
